### ISSUE TITLE
[FeatureRequest] Move to poetry

### ISSUE THREAD

**Issue by IlyaMichlin** [PythonNest/PyNest#11]
It might be better to move to Poetry to manage the python packages and releases.

**Comment by ELC** [comment]
Maybe also considering pipenv instead of poetry or pdm?

**Comment by RoyNoymanW** [comment]
The problem with poetry is the lack of support when it comes to constraints vs requirements.
Why do you consider moving to poetry?

**Comment by ELC** [comment]
@RoyNoymanW I personally prefer pipenv over poetry

There are no tools for locking minimal dependencies but both poetry and pipenv provide support for locking latests compatible dependencies with minimal constraints

**Comment by ItayTheDar** [comment]
@IlyaMichlin @ELC poetry is now supported! Thank you guys for all the help!
