### ISSUE TITLE
Change Absolute imports to Relative imports into examples

### ISSUE THREAD

**Issue by simonandres182** [PythonNest/PyNest#22]
Hello, I cloned the PyNest repository to try out the examples and find out that the imports in the examples project are Absolute and it would be easy to use Relative imports so it can be run in a easy way.. I have already made the changes so if the community like the idea I will push the changes.

From
**from examples.nest_products.src.users.users_service import UsersService
from examples.nest_products.src.users.users_model import User**

to

**from .users_service import UsersService
from .users_model import User**

**Comment by ItayTheDar** [comment]
Hi @simonandres182! that's sound like a great fix to add, could you open pr with those changes? tag me as a reviewer (Oh, and pull before because iv'e pushed new changes)
