### ISSUE TITLE
[UpgradeDependecies] Upgrade Pydantic to v2, FastAPI  > 0.100.0, beanie > 1.21.0

### ISSUE THREAD

**Issue by ItayTheDar** [PythonNest/PyNest#30]
## Description

This issue is to track the upgrade of key dependencies in the PyNest project. The upgrades are necessary to ensure compatibility with the latest versions and to leverage new features and improvements in these libraries.

## Dependencies to Upgrade

1. **Pydantic**: Upgrade to version 2.
   - **Reason**: Pydantic version 2 includes significant improvements in performance (rust backbone) and bug fixes that can enhance the robustness of data validation in PyNest.

2. **FastAPI**: Upgrade to version 0.100.0 or higher.
   - **Reason**: Newer versions of FastAPI offer enhanced performance, better error handling, and additional features that can improve the API development experience in PyNest.

3. **Beanie**: Upgrade to version 1.21.0 or higher.
   - **Reason**: Beanie's newer versions might include optimizations and new functionalities that are beneficial for database interactions within PyNest.

## Expected Benefits

- Improved performance and stability.
- Access to new features and optimizations in the upgraded libraries.
- Better compatibility with other dependencies and tools.

## Considerations

- Ensure compatibility with existing codebase and functionalities.
- Thorough testing is required to validate that the upgrades do not introduce any regressions or breaking changes.

---

This upgrade is crucial for maintaining the project's relevance and efficiency. Contributions and discussions on how to best approach these upgrades are welcome.

**Comment by uriafranko** [comment]
@ItayTheDar,

Important to keep in mind that Pydantic V2 has a lot of changes and a lot of deprecated functions.
I wouldn't be hurry to change unless it has full backward compatibility.

**Comment by ItayTheDar** [comment]
@uriafranko have you experienced this migration? Does the improvement in performance is that good? And since PyNest is rely on fastapi, then most of the migration has been done already.

**Comment by geovalexis** [comment]
Pydantic v2 comes with huge improvements over previous version. FastApi is heavily relied on Pydantic and its team has already completed the full upgrade. I don't concibe any new projects starting from a <2 version of Pydantic. Please, this upgrade is necessary and it's the only thing holding me up from using this library.

**Comment by ItayTheDar** [comment]
Hi @geovalexis ,
I'm planning to do that migration very soon.

**Comment by ItayTheDar** [comment]
@uriafranko @geovalexis Pydantic v2 is now supported! Thank you guys so much for all the help

**Comment by uriafranko** [comment]
Best project ever!
