### ISSUE TITLE
Purpose of Automatically Generated requirements.txt in New Project Creation

### ISSUE THREAD

**Issue by K-dash** [PythonNest/PyNest#55]
Thank you for your excellent work on this project!
After following the documentation to install and run it locally, I have a question regarding the use of the CLI command to create a new project (`pynest create-nest-app -n my_app_name -db postgresql`). 

This command generates a `requirements.txt` file within the new project directory, which seems to contain only the `pynest-api` package.

Could you clarify the intended purpose of this `requirements.txt`? 
It appears that running the pyNest CLI commands presupposes the prior installation of the `pynest-api` package, typically done using a `requirements.txt` that users prepare in advance.

Given this context, I am curious if the automatic generate of this file is necessary, or if I might be overlooking something.
Your insights would be greatly appreciated.

**Comment by ItayTheDar** [comment]
Hi @K-dash 

Thank you for your kind words and for bringing up this question! I appreciate your engagement with the project and your effort to understand its structure.

The `requirements.txt` file generated by the `pynest create-nest-app` command is indeed intended primarily for future use, particularly in scenarios like Docker deployments. This file simplifies the process of setting up a consistent environment for the application, ensuring that `pynest-api` and any other dependencies are correctly installed.!

That said, I'm always looking for ways to improve the project. If you have any suggestions or ideas on how to better handle the generation of the `requirements.txt` file, or if you think there's a more efficient approach, I'd love to hear your thoughts. Your feedback is invaluable in making `pynest` more user-friendly and robust.

Thanks again for your input

**Comment by K-dash** [comment]
Hi @ItayTheDar 

Thank you for your response!

I now understand that it is intended for deployments using Docker, which makes perfect sense. 

I also believe that placing the requirements.txt within the projects created by the pynest command is appropriate for the following reasons:

- It allows independent management of dependencies for each project when multiple projects are created using the pynest command.
- It adopts a similar approach to NestJS. 
  - Because pyNest is inspired by NestJS and faithfully reproduces NestJs implementation.

I apologize for my lack of knowledge. I will close this issue.

I continue to support the development of this project!!
