### ISSUE TITLE
add pydantic v2 suport

### ISSUE THREAD

**Issue by victorgabrieldeon** [PythonNest/PyNest#80]

**Comment by tjmcdonough** [comment]
I can't use pynest until the latest version of pydantic is supported

**Comment by ItayTheDar** [comment]
@tjmcdonough Hi Tom! 
I am well aware of that, there is an open pr that supposed to do that, among other things that will takes pynest to the next level! I will ping you once the pr will be merged!

**Comment by ItayTheDar** [comment]
@tjmcdonough pydantic v2 is now supported! Sorry for the long wait. LMK if you need any assistant with embracing pynest with pydantic v2
